=== sachinamaharjan/sachinamaharjan.github.io/js/lodges.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Lodges -->
    <xs:element name="lodges">
        <xs:complexType>
            <xs:sequence>
                <!-- Lodge 1 -->
                <xs:element name="lodge1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int"/>
                            <xs:element name="top" type="xs:int"/>
                            <xs:element name="left" type="xs:int"/>
                            <xs:element name="width" type="xs:int"/>
                            <xs:element name="height" type="xs:int"/>
                            <xs:element name="capacity" type="xs:int"/>
                            <xs:element name="cost" type="xs:int"/>
                            <xs:element name="startDate" type="xs:date"/>
                            <xs:element name="endDate" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <!-- Lodge 2 -->
                <xs:element name="lodge2">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int"/>
                            <xs:element name="top" type="xs:int"/>
                            <xs:element name="left" type="xs:int"/>
                            <xs:element name="width" type="xs:int"/>
                            <xs:element name="height" type="xs:int"/>
                            <xs:element name="capacity" type="xs:int"/>
                            <xs:element name="cost" type="xs:int"/>
                            <xs:element name="startDate" type="xs:date"/>
                            <xs:element name="endDate" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <!-- Lodge 3 -->
                <xs:element name="lodge3">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int"/>
                            <xs:element name="top" type="xs:int"/>
                            <xs:element name="left" type="xs:int"/>
                            <xs:element name="width" type="xs:int"/>
                            <xs:element name="height" type="xs:int"/>
                            <xs:element name="capacity" type="xs:int"/>
                            <xs:element name="cost" type="xs:int"/>
                            <xs:element name="startDate" type="xs:date"/>
                            <xs:element name="endDate" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <!-- Lodge 4 -->
                <xs:element name="lodge4">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int"/>
                            <xs:element name="top" type="xs:int"/>
                            <xs:element name="left" type="xs:int"/>
                            <xs:element name="width" type="xs:int"/>
                            <xs:element name="height" type="xs:int"/>
                            <xs:element name="capacity" type="xs:int"/>
                            <xs:element name="cost" type="xs:int"/>
                            <xs:element name="startDate" type="xs:date"/>
                            <xs:element name="endDate" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <!-- Lodge 5 -->
                <xs:element name="lodge5">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int"/>
                            <xs:element name="top" type="xs:int"/>
                            <xs:element name="left" type="xs:int"/>
                            <xs:element name="width" type="xs:int"/>
                            <xs:element name="height" type="xs:int"/>
                            <xs:element name="capacity" type="xs:int"/>
                            <xs:element name="cost" type="xs:int"/>
                            <xs:element name="startDate" type="xs:date"/>
                            <xs:element name="endDate" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <!-- Lodge 6 -->
                <xs:element name="lodge6">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int"/>
                            <xs:element name="top" type="xs:int"/>
                            <xs:element name="left" type="xs:int"/>
                            <xs:element name="width" type="xs:int"/>
                            <xs:element name="height" type="xs:int"/>
                            <xs:element name="capacity" type="xs:int"/>
                            <xs:element name="cost" type="xs:int"/>
                            <xs:element name="startDate" type="xs:date"/>
                            <xs:element name="endDate" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <!-- Lodge 7 -->
                <xs:element name="lodge7">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int"/>
                            <xs:element name="top" type="xs:int"/>
                            <xs:element name="left" type="xs:int"/>
                            <xs:element name="width" type="xs:int"/>
                            <xs:element name="height" type="xs:int"/>
                            <xs:element name="capacity" type="xs:int"/>
                            <xs:element name="cost" type="xs:int"/>
                            <xs:element name="startDate" type="xs:date"/>
                            <xs:element name="endDate" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <!-- Lodge 8 -->
                <xs:element name="lodge8">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int"/>
                            <xs:element name="top" type="xs:int"/>
                            <xs:element name="left" type="xs:int"/>
                            <xs:element name="width" type="xs:int"/>
                            <xs:element name="height" type="xs:int"/>
                            <xs:element name="capacity" type="xs:int"/>
                            <xs:element name="cost" type="xs:int"/>
                            <xs:element name="startDate" type="xs:date"/>
                            <xs:element name="endDate" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <!-- Lodge 9 -->
                <xs:element name="lodge9">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int"/>
                            <xs:element name="top" type="xs:int"/>
                            <xs:element name="left" type="xs:int"/>
                            <xs:element name="width" type="xs:int"/>
                            <xs:element name="height" type="xs:int"/>
                            <xs:element name="capacity" type="xs:int"/>
                            <xs:element name="cost" type="xs:int"/>
                            <xs:element name="startDate" type="xs:date"/>
                            <xs:element name="endDate" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <!-- Lodge 10 -->
                <xs:element name="lodge10">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int"/>
                            <xs:element name="top" type="xs:int"/>
                            <xs:element name="left" type="xs:int"/>
                            <xs:element name="width" type="xs:int"/>
                            <xs:element name="height" type="xs:int"/>
                            <xs:element name="capacity" type="xs:int"/>
                            <xs:element name="cost" type="xs:int"/>
                            <xs:element name="startDate" type="xs:date"/>
                            <xs:element name="endDate" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sachinamaharjan/sachinamaharjan.github.io/js/lodges.xml
<?xml version="1.0" encoding="UTF-8"?>
<lodges xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="lodges.xsd">
    <lodge1>
        <id>1</id>
        <top>20</top>
        <left>20</left>
        <width>50</width>
        <height>50</height>
        <capacity>4</capacity>
        <cost>100</cost>
        <startDate>2024-06-01</startDate>
        <endDate>2024-06-10</endDate>
    </lodge1>
    <lodge2>
        <id>2</id>
        <top>80</top>
        <left>20</left>
        <width>50</width>
        <height>50</height>
        <capacity>4</capacity>
        <cost>150</cost>
        <startDate>2024-06-15</startDate>
        <endDate>2024-06-25</endDate>
    </lodge2>
    <lodge3>
        <id>3</id>
        <top>140</top>
        <left>20</left>
        <width>50</width>
        <height>50</height>
        <capacity>6</capacity>
        <cost>200</cost>
        <startDate>2024-07-01</startDate>
        <endDate>2024-07-10</endDate>
    </lodge3>
    <lodge4>
        <id>4</id>
        <top>200</top>
        <left>460</left>
        <width>50</width>
        <height>50</height>
        <capacity>6</capacity>
        <cost>250</cost>
        <startDate>2024-06-05</startDate>
        <endDate>2024-06-15</endDate>
    </lodge4>
    <lodge5>
        <id>5</id>
        <top>100</top>
        <left>140</left>
        <width>50</width>
        <height>50</height>
        <capacity>2</capacity>
        <cost>75</cost>
        <startDate>2024-06-20</startDate>
        <endDate>2024-06-30</endDate>
    </lodge5>
    <lodge6>
        <id>6</id>
        <top>160</top>
        <left>140</left>
        <width>50</width>
        <height>50</height>
        <capacity>2</capacity>
        <cost>90</cost>
        <startDate>2024-07-05</startDate>
        <endDate>2024-07-15</endDate>
    </lodge6>
    <lodge7>
        <id>7</id>
        <top>220</top>
        <left>140</left>
        <width>50</width>
        <height>50</height>
        <capacity>2</capacity>
        <cost>90</cost>
        <startDate>2024-07-20</startDate>
        <endDate>2024-07-30</endDate>
    </lodge7>
    <lodge8>
        <id>8</id>
        <top>220</top>
        <left>220</left>
        <width>50</width>
        <height>50</height>
        <capacity>2</capacity>
        <cost>80</cost>
        <startDate>2024-08-01</startDate>
        <endDate>2024-08-10</endDate>
    </lodge8>
    <lodge9>
        <id>9</id>
        <top>160</top>
        <left>220</left>
        <width>50</width>
        <height>50</height>
        <capacity>2</capacity>
        <cost>85</cost>
        <startDate>2024-08-15</startDate>
        <endDate>2024-08-25</endDate>
    </lodge9>
    <lodge10>
        <id>10</id>
        <top>280</top>
        <left>220</left>
        <width>50</width>
        <height>50</height>
        <capacity>8</capacity>
        <cost>300</cost>
        <startDate>2024-09-01</startDate>
        <endDate>2024-09-10</endDate>
    </lodge10>
</lodges>
